---
driver:
  name: docker
  use_sudo: false
  provision_command: apt-get install -y curl wget net-tools

provisioner:
  name: chef_zero
  encrypted_data_bag_secret_key_path: 'test/integration/encrypted_data_bag_secret'

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec

platforms:
  - name: debian-8
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[np-deluge::default]
    attributes:

suites:
  - name: default
    run_list:
      - recipe[np-web::default]
      - recipe[np-web::static_sites]
    attributes:
      np_web:
        static_sites:
          - example.com
          - example.org
