name 'np-web'
maintainer 'Nick Pegg'
maintainer_email 'nick@nickpegg.com'
license 'all_rights'
description 'Sets up websites that I host'
long_description 'Sets up websites that I host'
version '0.1.0'
